### ISSUE TITLE
Question on how to handle 2 inverters via MQTT in HA

### ISSUE THREAD

**Issue by RienduPre** [johanmeijer/grott#180]
Hi Johan,

This is my environment:
I have 2 inverters (MIC 2500TL-X((ShineWifi-X) and a MOD 9000TL3-X (ShineLan))
I use Home Assistant (without Node-Red)
I want to make use of the Growatt app and also have the data via MQTT in HA
I have a running docker instance on my QNAP NAS based on the ledidobe/grott docker version 2.6.1.g 
The MIC 2500TL-X is reconfigured to use the Grott server and this is running smoothly
Now I want to add my other inverter and have a couple of questions:

- If I add the other inverter, MQTT topic would be overwriten by the other one, I found some issues discussing this but could not figure out how to solve this.
- What is the directory in the docker to put the grott.ini file in (I like to reroute this folder to a NAS folder to configure the setting easily.)
- What version off Grott should I be using?

Many thanks in advance and keep up the good work.

Best regards,
Rien

**Comment by johanmeijer** [comment]
At this moment it is a challenge for Grott if you use 2 different type of inverters (because you have to specify invtype=tl3 for the 9000TL3-X. This will be solved by the pull request by @markt-asf as described in #169. The you can specify invtype per inverterid. 

I will add this pull request to Grott somewhere this week (need to test it with my testware to  be sure it works for most of the users). Give a couple of days. 

It is possible to add inverter serial to the MQTT topic name: 
Add mqttinverterintopic = True to MQTT section of grott.ini or use  qmqttinverterintopic = "True"

Add the other end the MQTT JSON is build in a way that per device (device JSON key) a separate (nested) JSON message with data details lis generated. I am not sure if this can be used within HA to distinguish the inverters.
