### ISSUE TITLE
influxdb stopped collecting after a while.

### ISSUE THREAD

**Issue by cracyfloyd** [johanmeijer/grott#279]
all seems to be running but after a while the collecting is stopping. when i am observe the log it seems to be all the collecting running fine. but when you are looking in detail you can see the time of the collecting is wrong.
For a long time after i start grott the time in the log (collecting time) is right.

![failure1](https://user-images.githubusercontent.com/57620791/217634584-178df226-8209-4ee2-8475-eecb67af3047.jpg)
![failure2](https://user-images.githubusercontent.com/57620791/217634612-d6872572-3cd3-4311-9ced-53304c1d320e.jpg)

**Comment by johanmeijer** [comment]
Some dataloggers show a big time drift (do not keep up with the real time) . I am not sure why,  bu, this seems to be a hardware error. 

The first time the inverter/datalogger  starts (in the morning) the growatt server sent a time command to set the clock (with the time/date in the zone you configured at the Growatt site). Normally this is done ones a day. So if the datalogger has a timing problem the time can vary during the day. 
Normally the datalogger date/time is inserted in the data and used by Grott to create the MQTT, PVOutput en Influxdb records, 

If there are problems with the time drift of the datalogger we can do some things to bypass the problems.

* Restart Grott at regular base (there will be a Time sync command sent from the Growatt site)
The question is how big if is the time drift and how often you have to do this. Advantage is that all records will be processed by Grott (also eventually "buffered"records because of interupted connection)  
* If you are using Grott server you can sent a time update command via the API.
Same Advantages and disadvantages as a above. 
* Let Grott ignore the date/time in the data record and use the Server date/time by specifying time = server (gtime="server")
If the time of the server Grott is running on is set oke (think about time zones etc) this will be a solution for real time data. With this parameter active, Grott will not proces buffered records because there is no clue about when this record is created. This might not be a real problem if there are no problems with the connection, 

I am not sure if a datalogger upgrade can fix or introduce this problems. But upfront I do not rule this out.

**Comment by cracyfloyd** [comment]
Very very thnx for your detailed information.

For me it seems thats the problem is solved by self. 2 days now are the collecting to influx are without to stop the collect and the time is every time correct in the log.  Now i use in the docker the env gtime=server, maybe this make it more stable. 

Thnx again Markus

**Comment by johanmeijer** [comment]
Super. Can we close this one?

**Comment by cracyfloyd** [comment]
Yes, you can close. it runs and runs and runs....
Thnx so much..
