### ISSUE TITLE
Getting negative value of previous day in the morning

### ISSUE THREAD

**Issue by saurjk** [johanmeijer/grott#446]
Hi, 

I am getting everyday between 8 to 9, I get a surge of negative value from the total of the previous day's value, for example:

![image](https://github.com/johanmeijer/grott/assets/596268/b980485a-28d2-4e26-9c9a-c4f73b1435be)

I see the following when looking through the sensor

![image](https://github.com/johanmeijer/grott/assets/596268/1efaa99b-d610-451a-b181-ee2f1a24a0d5)

which probably explains the reason for the negative values in the morning. How would I fix this? Do I need to change something in the ini file or am I using the wrong sensor? I am using :  Power Generation - Total (eactotal)

Thanks.

**Comment by Neflardio** [comment]
You need to use "lifetime solar generation" sensor rather than the daily solar generation sensor when configuring the energy dashboard in HA.

**Comment by Neflardio** [comment]
If those sensors represent the total solar generation of your system thus far, they will work. They both have the same value so either will work. The main thing is using a sensor that does not give a daily reading. HA compares the last read value with the new value to give work out solar generation. A sensor with a daily readout resets to 0, which is why HA will give a value equivalent to negative previous day generation in the morning if using a daily sensor.
