### ISSUE TITLE
Old value messing up data

### ISSUE THREAD

**Issue by dliebrand** [johanmeijer/grott#503]
Hi,
I have grott succesfully running using docker. Sends the data to mqtt. Works flawless until 5 Jan. 
Grott sends a record with data from 5 January 05.16 to mqtt. 

Rebuild grott docker. Restarted the shinebox. 

![Screenshot_2024-01-07-13-27-22-126_at.tripwire.mqtt.client-edit.jpg](https://github.com/johanmeijer/grott/assets/40805908/198c8996-6a41-4958-9777-44962a4f07ed)

Don't know to stop sending these values. I think it is buffered data from the shinebox which it tries to send over and over. 
Home assistant checks this data field: generated today / epv1today. And that switches to 0 and sometimes the real value.

**Comment by johanmeijer** [comment]
It looks like old data indeed. You can see this because bufferd is yes (and because fof the date/time normally). 

If you do not want this (because your consumers can not handle this)  then please specify sendbuf = False (or for docker the environment gsendbuf = False). Grott will ignore the buffered records then.
